# How a piece of Ceres is declared.
#
# The five libraries are identical on the inside, so they're declared with a function instead of
# five CMakeLists.txt files drifting out of sync. The only thing that changes between them is the
# name and what they depend on, and that's exactly what gets passed as parameters.
#
# About the globs: for as long as the migration lasts, files are discovered on their own. That's
# the right call now - moving a .cpp from Ceres-ASM-old into place shouldn't also require editing
# a CMakeLists - and the wrong one once the migration is done, because a glob can't warn you that
# someone left a file outside the tree. CONFIGURE_DEPENDS makes CMake look again on every build,
# so a new file shows up without reconfiguring by hand.
#
#   >>> Once the migration is done: replace the globs with explicit lists. <<<

include_guard(GLOBAL)

# The placeholder translation unit's text. A static library needs at least one .cpp for CMake to
# know which linker to treat it with, and during the migration some src/ directories are still
# empty. As soon as a real .cpp shows up, this stops being compiled on its own.
set(CERES_PLACEHOLDER_SOURCE [[
// Generated by CMake. Not version-controlled and never needs touching.
//
// This library doesn't have its own sources yet: the code is still in Ceres-ASM-old, waiting to
// be migrated. An empty static file makes the MSVC linker warn (LNK4221) and keeps CMake from
// deducing the target's language, so here's a symbol and nothing else. As soon as there's a
// .cpp in src/, this file drops out of the build without anyone deleting it.
//
// The symbol carries the library's name, and that's not cosmetic: five static files with the
// same external symbol are five duplicate definitions waiting for something to reference them.
// Nothing happens today because the linker doesn't pull in a member nobody asks for, but that's
// luck, not design. And ceres::detail belongs to common/, not here: hence the suffix.

namespace ceres::detail
{
	int placeholderTranslationUnit_@name@() noexcept;
	int placeholderTranslationUnit_@name@() noexcept { return 0; }
}
]])

# ceres_add_library(<name> [DEPENDS <name> ...])
#
# Creates ceres_<name> (static) and the ceres::<name> alias. include/ headers are public and
# src/ ones aren't: the boundary stops being a convention and becomes a compile error the moment
# anyone tries to cross it.
function(ceres_add_library name)
	cmake_parse_arguments(PARSE_ARGV 1 ARG "" "" "DEPENDS")

	set(root "${CMAKE_CURRENT_SOURCE_DIR}")
	set(target "ceres_${name}")

	file(GLOB_RECURSE sources CONFIGURE_DEPENDS "${root}/src/*.cpp")
	file(GLOB_RECURSE private_headers CONFIGURE_DEPENDS "${root}/src/*.h")
	file(GLOB_RECURSE public_headers CONFIGURE_DEPENDS "${root}/include/*.h")

	set(compiled ${sources})
	if(NOT compiled)
		set(placeholder "${CMAKE_CURRENT_BINARY_DIR}/${target}_placeholder.cpp")
		if(NOT EXISTS "${placeholder}")
			# string(CONFIGURE) to substitute @name@: the content of a bracket-argument is
			# stored literally, so a ${} inside it wouldn't expand when writing it out.
			string(CONFIGURE "${CERES_PLACEHOLDER_SOURCE}" placeholder_text @ONLY)
			file(WRITE "${placeholder}" "${placeholder_text}")
		endif()
		set(compiled "${placeholder}")
	endif()

	# No loose files in this list. When Visual Studio adds a new file to a CMake project, it
	# edits the nearest add_library() it can find - and the one it finds is this one, shared by
	# all five libraries, so one library's header ends up claimed by all of them with a relative
	# path that doesn't resolve from any of them. The globs above already pick up any new file:
	# just create the file in its folder and that's it.
	add_library(${target} STATIC ${compiled} ${private_headers} ${public_headers})
	add_library(ceres::${name} ALIAS ${target})

	# BUILD_INTERFACE and not a bare path: the day this gets installed or split out into its own
	# repository, the source tree's path won't mean anything to whoever consumes it.
	target_include_directories(${target}
		PUBLIC  "$<BUILD_INTERFACE:${root}/include>"
		PRIVATE "${root}/src")

	target_link_libraries(${target}
		PUBLIC  ceres::settings
		PRIVATE ceres::warnings)

	foreach(dependency IN LISTS ARG_DEPENDS)
		target_link_libraries(${target} PUBLIC ceres::${dependency})
	endforeach()

	set_target_properties(${target} PROPERTIES FOLDER "libs")

	# So the Visual Studio Solution Explorer shows the real tree instead of a flat list.
	if(public_headers)
		source_group(TREE "${root}/include" PREFIX "include" FILES ${public_headers})
	endif()
	if(sources OR private_headers)
		source_group(TREE "${root}/src" PREFIX "src" FILES ${sources} ${private_headers})
	endif()

	list(LENGTH sources source_count)
	set_property(GLOBAL APPEND PROPERTY CERES_MIGRATION_STATUS "${name}=${source_count}")
endfunction()

# ceres_add_tests(<name>)
#
# A library's unit suite, if it already has files under tests/. Called from the library's own
# CMakeLists, next to its ceres_add_library().
function(ceres_add_tests name)
	if(NOT CERES_BUILD_TESTS)
		return()
	endif()

	file(GLOB sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/tests/*.cpp")
	if(NOT sources)
		return()
	endif()

	if(NOT TARGET ceres_test_main)
		message(STATUS "ceres: ${name} already has tests, but tests/framework/main.cpp is missing - suite skipped")
		return()
	endif()

	set(target "ceres_${name}_tests")
	add_executable(${target} ${sources})
	target_link_libraries(${target} PRIVATE ceres::${name} ceres::test_main ceres::warnings)

	# A library's suite does see its private headers. It's the only exception to the boundary,
	# and it's deliberate: a unit test that can only touch the public API isn't unitary. It's
	# needed as soon as a header moves down from include/ to src/ - test_json and test_expression
	# test exactly the things that have no business being in ceres-debug's API.
	target_include_directories(${target} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")

	set_target_properties(${target} PROPERTIES FOLDER "tests")

	add_test(NAME ${name} COMMAND ${target})
endfunction()

# ceres_report_migration_status()
#
# At configure time, a tally of what's left to move. Cheap to write and avoids the "has this
# been migrated yet?" question every session.
function(ceres_report_migration_status)
	get_property(entries GLOBAL PROPERTY CERES_MIGRATION_STATUS)

	set(pending "")
	set(done "")
	foreach(entry IN LISTS entries)
		string(REPLACE "=" ";" parts "${entry}")
		list(GET parts 0 name)
		list(GET parts 1 count)
		if(count EQUAL 0)
			list(APPEND pending "${name}")
		else()
			list(APPEND done "${name} (${count})")
		endif()
	endforeach()

	message(STATUS "")
	message(STATUS "Ceres ${PROJECT_VERSION} - C++${CMAKE_CXX_STANDARD}, ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
	if(done)
		list(JOIN done ", " text)
		message(STATUS "  with sources: ${text}")
	endif()
	if(pending)
		list(JOIN pending ", " text)
		message(STATUS "  to migrate  : ${text}")
	endif()
	if(NOT TARGET ceres)
		message(STATUS "  executable  : no apps/cli/src/main.cpp yet")
	endif()
	message(STATUS "")
endfunction()
